# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:6.0.1
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: zedb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: zedb
      ME_CONFIG_MONGODB_URL: mongodb://admin:zedb@mongo:27017/